event_loop_interval: 10ms
queue_size: 1000
devices:
  device-1:
    type: controller
    protocol: mock
    endpoint: mock://device-1
    parameters: {}
    timeout: 10s
    retry_count: 0
device_groups:
  main_workspace:
    name: Main Workspace
    description: Primary 3-axis cartesian workspace
    device_ids:
      - device-1
    dimensions:
      X:
        name: X
        type: linear
        min_value: -1000.0
        max_value: 1000.0
        home_value: 0.0
        max_velocity: 100.0
        max_accel: 50.0
        units: mm
        invert: false
      Y:
        name: Y
        type: linear
        min_value: -1000.0
        max_value: 1000.0
        home_value: 0.0
        max_velocity: 100.0
        max_accel: 50.0
        units: mm
        invert: false
      Z:
        name: Z
        type: linear
        min_value: -500.0
        max_value: 500.0
        home_value: 0.0
        max_velocity: 50.0
        max_accel: 25.0
        units: mm
        invert: false
    kinematics:
      type: cartesian
      workspace:
        shape: box
        dimensions:
          width: 2000.0
          depth: 2000.0
          height: 1000.0
        constraints: {}
      transforms: {}
      constraints: {}
    capabilities:
      linear_motion: true
      home_all: true
      emergency_stop: true
safety:
  enable_limits: true
  enable_emergency: true
  max_temperature: 80
  min_voltage: 12
  watchdog_timeout: 10s
ipc:
  type: tcp
  address: 127.0.0.1
  port: 28080
  timeout: 5s
  buffer_size: 1024
task_templates:
  home_all:
    name: Home All Axes
    description: Home all axes to their home positions
    type: sequence
    parameters:
      mode: sequential
      stop_on_error: true
    nodes:
      - id: home-x
        type: home
        parameters:
          axes:
            - axis-x
      - id: home-y
        type: home
        parameters:
          axes:
            - axis-y
      - id: home-z
        type: home
        parameters:
          axes:
            - axis-z
    timeout: 30s
    priority: 1
  io_check:
    name: IO Status Check
    description: Check IO status before operation
    type: sequence
    parameters:
      mode: sequential
      stop_on_error: true
    nodes:
      - id: check-sensor-1
        type: io
        parameters:
          action: read
          channel: sensor-1
          device_id: device-1
      - id: check-sensor-2
        type: io
        parameters:
          action: read
          channel: sensor-2
          device_id: device-1
    timeout: 5s
    priority: 2
  motor_start_sequence:
    name: Motor Start Sequence
    description: Start motors with delay between each
    type: sequence
    parameters:
      mode: sequential
      stop_on_error: true
    nodes:
      - id: start-motor-1
        type: motor_control
        parameters:
          action: start
          device_id: device-1
          motor_id: motor-1
          speed: 100
      - id: delay-1
        type: delay
        parameters:
          duration: 2s
          unit: s
      - id: start-motor-2
        type: motor_control
        parameters:
          action: start
          device_id: device-1
          motor_id: motor-2
          speed: 150
    timeout: 10s
    priority: 2
command_mappings:
  emergency_stop:
    abstract_command: emergency_stop
    description: 急停系统
    nodes:
      - id: emergency-stop-motors
        type: motor_control
        parameters:
          action: stop
          device_id: device-1
          motor_id: all
    priority: 0
    timeout: 5s
  home:
    abstract_command: home
    description: 回零所有轴
    template: home_all
    priority: 1
    timeout: 30s
  initialize:
    abstract_command: initialize
    description: 初始化系统
    nodes:
      - id: init-self-check
        type: sequence
        parameters:
          mode: sequential
          stop_on_error: true
        children:
          - id: init-io-check
            type: io
            parameters:
              action: read
              channel: system-status
              device_id: device-1
          - id: init-delay
            type: delay
            parameters:
              duration: 1s
              unit: s
      - id: init-home
        type: sequence
        parameters:
          mode: sequential
          stop_on_error: true
        children:
          - id: home-x
            type: home
            parameters:
              axes:
                - axis-x
          - id: home-y
            type: home
            parameters:
              axes:
                - axis-y
          - id: home-z
            type: home
            parameters:
              axes:
                - axis-z
    priority: 1
    timeout: 1m0s
  reset:
    abstract_command: reset
    description: 复位系统到初始状态
    nodes:
      - id: stop-all
        type: motor_control
        parameters:
          action: stop
          device_id: device-1
          motor_id: all
      - id: reset-delay
        type: delay
        parameters:
          duration: 2s
          unit: s
    priority: 1
    timeout: 15s
  safety_check:
    abstract_command: safety_check
    description: 安全检查
    template: safety_check
    priority: 1
    timeout: 15s
  self_check:
    abstract_command: self_check
    description: 执行系统自检
    template: io_check
    priority: 1
    timeout: 10s
  start:
    abstract_command: start
    description: 启动系统
    template: safety_check
    priority: 2
    timeout: 20s
  stop:
    abstract_command: stop
    description: 停止系统
    nodes:
      - id: stop-motors
        type: motor_control
        parameters:
          action: stop
          device_id: device-1
          motor_id: all
    priority: 1
    timeout: 10s
